### ISSUE TITLE
Plugin stopped to work due to CORS issue

### ISSUE THREAD

**Issue by antonjuls** [SaraVieira/svg-to-jsx#16]
Hi! 
First of all - thanks a lot for the plugin, this is a great and very useful tool!

But recently plugin stopped to work properly. It wont transform SVG code anymore using "React Native" or "TypeScript" options.
The console of the Figma is showing the issue with request to plugin backend server.

<img width="736" alt="Screen Shot 2021-03-06 at 1 45 16 PM" src="https://user-images.githubusercontent.com/4677491/110205788-bdcb5600-7e82-11eb-8e51-5a7591e78e24.png">

Would be great to fix this issue, working without this plugin is not so cool ;)

Thanks!

**Comment by SaraVieira** [comment]
Hey!

Vercel seemed to have renamed everything that ended in .now.sh 

Will take a look today! Sorry for the issue

**Comment by SaraVieira** [comment]
Hey! 

Just pushed a fix, can you confirm it's working on your side?

**Comment by antonjuls** [comment]
@SaraVieira yes, it's working now! Thanks a lot!

**Comment by SaraVieira** [comment]
Nice! Quick fix 🎉
