### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by philipamour** [SaraVieira/svg-to-jsx#26]
Doesn't seem to work anymore

**Comment by SaraVieira** [comment]
Will take a look today

**Comment by philipamour** [comment]
Thanks! 😊

**Comment by SaraVieira** [comment]
Seems my account on vercel was blocked because one of my sites got a huge spike in traffic :(

**Comment by SaraVieira** [comment]
Is it working again? My account was unblocked

**Comment by philipamour** [comment]
Works perfectly well! 😊 Thank you so much! 😊

**Comment by SaraVieira** [comment]
Awesome!!
